global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'host.docker.internal:9101' ]

  - job_name: 'product_write_service'
    static_configs:
      - targets: [ 'host.docker.internal:8002' ]

  - job_name: 'product_read_service'
    static_configs:
      - targets: [ 'host.docker.internal:8003' ]

